"""add_steps_and_embed_html

Revision ID: 20aeae09ef25
Revises: 7948834e4b97
Create Date: 2026-05-26 18:36:10.439437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20aeae09ef25'
down_revision: Union[str, Sequence[str], None] = '7948834e4b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('embed_html', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('steps', sa.JSON(), nullable=True))
    op.alter_column('recipes', 'raw_caption',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'raw_caption',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('recipes', 'steps')
    op.drop_column('recipes', 'embed_html')
    # ### end Alembic commands ###
