"""add_recipe_tags

Revision ID: 39f972621a72
Revises: 55872d519587
Create Date: 2026-05-27 13:09:27.271904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39f972621a72'
down_revision: Union[str, Sequence[str], None] = '55872d519587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('effort', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recipes', sa.Column('time_minutes', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('is_batch_prep', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('recipes', sa.Column('protein_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'protein_level')
    op.drop_column('recipes', 'is_batch_prep')
    op.drop_column('recipes', 'time_minutes')
    op.drop_column('recipes', 'effort')
    op.drop_column('recipes', 'servings')
    # ### end Alembic commands ###
