"""add_calorie_level_protein_source

Revision ID: 4a7471a4841e
Revises: 39f972621a72
Create Date: 2026-05-27 13:24:37.890123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a7471a4841e'
down_revision: Union[str, Sequence[str], None] = '39f972621a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('calorie_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recipes', sa.Column('protein_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'protein_source')
    op.drop_column('recipes', 'calorie_level')
    # ### end Alembic commands ###
