"""initial_schema

Revision ID: 7948834e4b97
Revises: 
Create Date: 2026-05-26 17:57:27.850302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7948834e4b97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_canonical_name'), 'inventory_items', ['canonical_name'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dish_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grocery_list_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_recipe_id'), 'ingredients', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredients_recipe_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_table('grocery_list_items')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_inventory_items_canonical_name'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
