"""add_is_favorited

Revision ID: da16d2003e30
Revises: 4a7471a4841e
Create Date: 2026-05-28 00:30:40.876971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da16d2003e30'
down_revision: Union[str, Sequence[str], None] = '4a7471a4841e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('is_favorited', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'is_favorited')
    # ### end Alembic commands ###
